apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing # Declares it public-facing
    alb.ingress.kubernetes.io/target-type: ip 
spec:
  predictor: 
    serviceAccountName: sa-minio-kserve
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "s3://mlpipeline/v2/artifacts/anomaly-detection-training/575fffd0-0ecc-4eb2-bb20-2aeaa4d06268/train-model-component/13f80e89-3b91-458c-9e0a-fc493aad3e4e/output_model"